version: "3.9"

services:
  api:
    build: ..
    command: uvicorn backend:create_app --factory --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    environment:
      - PYTHONUNBUFFERED=1

